### ISSUE TITLE
Meeting preparation script

### ISSUE THREAD

**Issue by felipefarias** [vintasoftware/Guidebook#15]

**Comment by filipeximenes** [comment]
30 min before meeting:
- Did you deploy whatever should be deployed?
- Do you have a phone with microfone?
- Is your microfone working?
- Is your camera working?

Tips:
- Have your camera in the height of your eyes and in front of you. Although this is a video meeting it should feel that you are looking face to face to the person. You will give a more professional impression and the client will fill more confident because you are "looking him in the eyes" and not facing the screen in a weird position.

**Comment by filipeximenes** [comment]
ALWAYS SEND A CALENDAR INVITE. Configure your calendar to send you notifications 1 day before (email) and 30 minutes before (preferably on your phone). Here is how to configure the default notification scheme for your calendar: https://support.google.com/calendar/answer/37242?hl=en.  This is important so you don't miss the meeting and have time to check if everything is well. Also, too much meetings is harmful to your productivity, so clients should get used to schedule meetings beforehand and not just hop in for a call at any time.

**Comment by felipefarias** [comment]
- When you speak with the client you're the voice of the company, so you need to be very professional;
- Always work the amount of hours agreed with the client;
- Take notes about the client's needs;
- Try not to be so informal. avoid the excessive use of slang;
- Always add the tasks on Trello after the meeting;
- It's your responsibility check and ask to the client for all the stuff that are missing in the project;
- Avoid to be on hold, if you need something, talk with your manager or with the client;
- Never say that something is easy or simple;
- Never lie to the client, when something goes wrong, be transparent;
- All the clients need to use Slack.
